FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    wget \
    git \
    gccgo-10 \
    make \
    findutils \
    gcc-multilib \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /build
COPY . .

# Compila con gccgo, forzando 32 bit e i flag anti-MMX
RUN find . -name "*.go" -not -path "./.git/*" -print0 | xargs -0 gccgo-10 \
    -m32 \
    -g \
    -O2 \
    -march=i586 \
    -mno-mmx \
    -mno-sse \
    -static \
    -static-libgcc \
    -o MP48WebService

CMD ["./MP48WebService"]