FROM debian:11-slim

RUN apt-get update && apt-get install -y \
    gccgo-10 \
    git \
    make \
    wget \
    && rm -rf /var/lib/apt/lists/*

RUN wget https://go.dev/dl/go1.15.15.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go1.15.15.linux-amd64.tar.gz && \
    mv /usr/local/go /usr/local/go1.15

ENV PATH=/usr/local/go1.15/bin:$PATH

WORKDIR /build
COPY . .

RUN go mod vendor && \
    export GOROOT=$(gccgo-10 -print-libgcc-file-name | sed 's|/lib/gcc/.*||') && \
    export GCCGO=gccgo-10 && \
    export GOOS=linux GOARCH=386 CGO_ENABLED=0 && \
    go build -compiler gccgo \
        -gccgoflags="-march=i586 -mno-mmx -mno-sse -static -static-libgcc -Wl,-static" \
        -mod=vendor \
        -ldflags="-s -w" \
        -o MP48WebService .

CMD ["./MP48WebService"]